# Generated by Django 3.2.9 on 2022-07-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0005_category_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
