# Generated by Django 4.0.6 on 2022-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0009_supplier_phone_supplier_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='profileimage',
            field=models.FileField(default=None, null=True, upload_to='profileimage/'),
        ),
    ]
