# Generated by Django 4.0.6 on 2022-07-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0011_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relation',
        ),
    ]
