# Generated by Django 4.0.6 on 2022-07-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0012_delete_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, default='ka', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, default='asd', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zipcode',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
