# Generated by Django 4.0.6 on 2022-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0015_alter_supplier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.TextField(max_length=50),
        ),
    ]
