# Generated by Django 4.0.6 on 2022-07-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0010_company_phone_company_profileimage'),
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userlist.supplier'),
        ),
    ]
