# Generated by Django 4.0.6 on 2022-07-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0002_product_supplied_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplied_by',
        ),
    ]
