# Generated by Django 4.0.6 on 2022-07-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0012_delete_relation'),
        ('product_details', '0003_remove_product_supplied_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userlist.supplier'),
        ),
    ]
