# Generated by Django 4.0.6 on 2022-07-31 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_details', '0004_product_supplied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
