# Generated by Django 4.0.6 on 2022-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0008_alter_product_supplied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET_NULL, to='product_details.categorie'),
        ),
    ]
