# Generated by Django 4.0.6 on 2022-07-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userlist', '0012_delete_relation'),
        ('product_details', '0005_alter_product_supplied_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsupplied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.product')),
                ('suppliedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlist.supplier')),
                ('suppliedto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlist.company')),
            ],
        ),
    ]
