# Generated by Django 4.0.6 on 2022-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_relationtable_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationtable',
            name='Approved',
        ),
        migrations.AddField(
            model_name='relationtable',
            name='Approval',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
