# Generated by Django 4.0.6 on 2022-08-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_remove_relationtable_approved_relationtable_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtable',
            name='Approval',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
