# Generated by Django 4.0.6 on 2022-10-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0004_alter_relationtable_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtable',
            name='Approval',
            field=models.CharField(default='N', max_length=50, null=True),
        ),
    ]
